import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, HeaderLeft, HeaderRight } from '../components/header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Prints Editor: NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <Header>
          <HeaderLeft>Logo</HeaderLeft>
          <HeaderRight>Price</HeaderRight>
        </Header>
      </div>
    </>
  )
}

export default Home
